name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Cache NPM dependencies
      - name: Cache NPM
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      # Cache NuGet packages
      - name: Cache NuGet
        id: nuget-cache
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      # Cache Playwright browsers
      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            playwright-browsers-${{ runner.os }}-

      # Install dependencies
      - name: Install dependencies
        run: |
          npm ci
          dotnet restore

      # Install Playwright browsers only if missing
      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      # Debug: Show cache status
      - name: Show cache debug info
        run: |
          echo "NPM Cache hit: ${{ steps.npm-cache.outputs.cache-hit }}"
          echo "NuGet Cache hit: ${{ steps.nuget-cache.outputs.cache-hit }}"
          echo "Playwright Cache hit: ${{ steps.playwright-cache.outputs.cache-hit }}"

      # Run .NET Playwright tests
      - name: Run .NET Playwright tests
        run: dotnet test --logger:"console;verbosity=detailed"

      # Upload report
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
