name: Playwright Tests (.NET)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      # Cache both NuGet and Playwright browsers
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

      - name: Build project
        run: dotnet build PlaywrightTests/PlaywrightTests.csproj --configuration Debug

      # Install Playwright browsers only when cache missed
      - name: Install Playwright browsers
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          bash PlaywrightTests/bin/Debug/net8.0/playwright.sh install --with-deps

      - name: Run tests
        run: dotnet test PlaywrightTests/PlaywrightTests.csproj --logger:"console;verbosity=detailed"
